# Generated by Django 3.1.4 on 2022-03-14 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20220314_0821'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Executives',
            new_name='Executive',
        ),
    ]
