# Generated by Django 3.1.4 on 2022-03-16 18:55

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20220314_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executive',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
