# Generated by Django 3.1.4 on 2022-03-17 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20220316_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/articles/'),
        ),
        migrations.AlterField(
            model_name='executive',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/executives/'),
        ),
    ]
